#!/bin/bash

echo "création de l'image docker..."
docker build -q -t calculator-app .

echo "Suppresion de l'image intermédiaire..."
idtosuppr=$(docker images | grep none | tr -s ' ' | cut -d ' ' -f3)
docker rmi "$idtosuppr"
echo "Supprimée avec succès ✔"

echo "Test de l'application : "
docker run --rm calculator-app
