#!/bin/bash

echo "création de l'image docker..."
docker build -t -q calculator-app .

echo "Suppresion de l'image intermédiaire"

echo "Supprimée avec succès ✔"

echo "Test de l'application : "
docker run --rm calculator-app